spring:
  application.name: gaming-enjoyment
  datasource:
    url: jdbc:postgresql://localhost:5432/gaming_enjoyment
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update